### ISSUE TITLE
Does not display lists needs access token? 

### ISSUE THREAD

**Issue by dvnnyburgx** [thobach/MMM-MicrosoftToDo#81]
Hello I am new to the magic mirror business and doing it as a class project. I am trying to do this to do list and I have followed every step correctly I believe but i get these error codes after exiting the mirror itself. 

[14.04.2022 17:15.05.399] [ERROR] [MMM-MicrosoftToDo]: getTodos / get access token: https://login.microsoftonline.com/common/oauth2/v2.0/token
[14.04.2022 17:15.05.402] [ERROR] [MMM-MicrosoftToDo]: Error: checkFetchStatus failed with status 'Bad Request' {"size":0,"timeout":0}

It just shows up on the mirror as the title and one unchecked box. I made sure I have active to do lists with the right names as I am using the listname instead of listID. Any help please?

**Comment by thobach** [comment]
@dvnnyburgx  The issue seems to be with generating the access token. I suggest to try again the whole installation in the Azure portal and update the oauth* configuration parameters accordingly. If you like you can also contact me on twitter with a direct message (https://twitter.com/thobach) and I'll let you know my email address to send me screenshots of the Azure portal configuration.

**Comment by Alex-lob** [comment]
Hello, I have the same problem after the MM ran for months without any problems.

**Comment by mithrandir80** [comment]
It looks like I have a similar problem after months of working perfectly. Error message in MagicMirror was that user could not be authenticated due to account expiration. After login in Azure/Microsoftonline I see a message:
The logged in user is not authorised to fetch tokens for extension ‘Microsoft_AAD_IAM’ because user is not a member of tenant. 

![D5C4FA55-A936-4D86-89D4-8EF63C6E2859](https://user-images.githubusercontent.com/73595314/168672915-7239e8c3-a7d2-4f67-9bfd-fa19113fac72.jpeg)
 
 
Any ideas to solve this issue (it used to worked like a charm ;-)

**Comment by mirko3000** [comment]
Same for me here, used to work still few days ago, now after fresh install I also get a bad request on login with my tokens:
```

18.05.2022 21:33.58.198] [ERROR] Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
    status: 400,
    statusText: 'Bad Request',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
```

**Comment by PieMasterCG** [comment]
same problem here, anyone have a solution?

**Comment by mithrandir80** [comment]
What worked for me was going through the azure process again. Following the steps in the tutorial from Client Secret Key Generation till the end. I deleted old secret key first but might work with two as well.

**Comment by thobach** [comment]
@mirko3000 @dvnnyburgx Does the workaround from @mithrandir80 work for you as well? You could also check first if the secret at this screen is not expired. 
![](https://user-images.githubusercontent.com/274056/174261960-68868cfe-d06b-4bfb-961b-92af8b40a374.png)

> What worked for me was going through the azure process again. Following the steps in the tutorial from Client Secret Key Generation till the end. I deleted old secret key first but might work with two as well.

**Comment by mirko3000** [comment]
@thobach: yes actually that solved my issue here. Maybe because my old client secret was valid for more than 2 years (not allowed anymore)? Anyhow, working now again, thanks all!
